# Generated by Django 5.2.8 on 2025-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('operation_data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='telegramlog',
            options={},
        ),
        migrations.AddField(
            model_name='telegramlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramlog',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
